hosts:
  - rfsoc4x2

fpgfile: /home/jackh/src/souk-firmware/firmware/src/souk_single_pipeline_4x2/outputs/souk_single_pipeline_4x2_2023-03-23_1118.fpg
lmkfile: rfsoc4x2_PL_122M88_REF_245M76.txt
lmxfile: rfsoc4x2_LMX_REF_245M76_OUT_491M52.txt

channelizer:
  fftshift: 0xffffffff
